### ISSUE TITLE
Concat Multiple Page into One with Page Break

### ISSUE THREAD

**Issue by anitgandhi** [alanshaw/markdown-pdf#109]
Is it possible to concatenate multiple MD files into a single PDF *with* full page breaks?

For example, a 1.5 page MD and a 2.5 page MD file combined into a 5 page (2+3) instead of 4?

**Comment by jpinkster** [comment]
Looking for the same thing!

**Comment by JelaniThompson** [comment]
same here

**Comment by prestonkyles** [comment]
same here

**Comment by alanshaw** [comment]
It is possible to have:

```
0-page.md
1-break.md
2-page.md
```

Where `1-break.md` has just:

```html
<div style="page-break-before: always;"></div>
<div style="page-break-before: always;"></div>
```

?...and then simply use [concat from paths](https://github.com/alanshaw/markdown-pdf#concatfrompathspaths-opts)?

https://developer.mozilla.org/en/docs/Web/CSS/page-break-before

**Comment by jpinkster** [comment]
@alanshaw ++ 

That worked perfectly .. sadly I never knew you could have html in a MD file haha 

Per your suggestion I just added the `<div style="page-break-after: always;"></div>` and a new line to the bottom of my MD files and ran the command again, and BOOM... page breaks are now working! 

_Note:_ I needed to add a new line at the end of the MD file because otherwise the next pages header was getting un-styled.

**Comment by anitgandhi** [comment]
Can't believe I didn't think of that. Thanks!

In case anyone in the future needs an easy way to do this:

```
function preProcessMd () {
	return through(function(data) {
		pageBreak = '\n\n<div style="page-break-before: always;"></div>\n\n'

		this.queue(data + pageBreak)
	})
}
 
var options = {
    preProcessMd: preProcessMd, 
}

markdownpdf(options).concat.from(mdDocs).to(finalPDF, function () {
  console.log("Created", finalPDF)
})
```
