### ISSUE TITLE
Text not selectable

### ISSUE THREAD

**Issue by MoOx** [alanshaw/markdown-pdf#16]
Currently using phantomjs make us unable to select text into the pdf. I'm assuming phantomjs render as png.
What about using another rendering tool like [pandoc](http://johnmacfarlane.net/pandoc/) ?

**Comment by meteormatt** [comment]
Issue is still here.

**Comment by anko** [comment]
@jpbochi @meteormatt 

Works on Linux.

If failing on OS X, that's caused by upstream ariya/phantomjs#10373, as [previously mentioned](https://github.com/alanshaw/markdown-pdf/issues/16#issuecomment-38856125). There's a fix for even further upstream at https://github.com/Vitallium/qtbase/pull/2. Ask there who to throw money at.
