### ISSUE TITLE
Does markdown-pdf run in browser?

### ISSUE THREAD

**Issue by cybertk** [alanshaw/markdown-pdf#61]
markdown-pdf is very awesome as a node.js bin/lib for PDF generation. Can I used it in browser to converting PDF on the fly?

**Comment by alanshaw** [comment]
It doesn't, but it could do with some code changes.

The basic idea is that markdown-pdf runs a browser (phantomjs) and then saves the PDF to a file. You could probably change the code so that the markdown input comes from an `<input type="file">` and have it render the html in an `<iframe>`, followed by invoking the print dialog with `window.print()` - from there you could save the output as a PDF.

You'd have to change the code considerably so its probably not something I'd add to markdown-pdf but it could be an interesting project to build.
