### ISSUE TITLE
Links do not render correctly

### ISSUE THREAD

**Issue by biofractal** [alanshaw/markdown-pdf#63]
The standard markdown link syntax were not rendering correctly with my markdown docs. To test if this was just me I used a standard [Lorum Ipsum](https://github.com/alanshaw/markdown-pdf/blob/master/test/fixtures/ipsum.md) MD text and got the same result (see screenshot). 

Can you help please?

![pdf](https://cloud.githubusercontent.com/assets/329603/9935896/3e29003a-5d51-11e5-92ff-e62d3be228a1.png)

**Comment by anko** [comment]
The default CSS inserts links' `href`s in parentheses. [This is the part that does it.](https://github.com/alanshaw/markdown-pdf/blob/master/html5bp/css/main.css#L246-L248)

You can disable that by putting this in your [custom CSS](https://github.com/alanshaw/markdown-pdf#optionscsspath):

```css
a[href]:after { content : "" }
```

Do keep in mind that readers won't otherwise know what that link refers to.

**Comment by biofractal** [comment]
Thanks for the quick reply. I understand now that this is a feature, not a bug. 

Nonetheless I am struggling to get the custom css to be noticed. I made the change you suggested to the `[module path]/markdown-pdf/css/pdf.css` that comes with the package but no joy. The help says the custom css path is the:

>Path to custom CSS file, relative to the current directory.

In this case, can you tell me what is the current directory? The root of the site or somewhere in the module package.

Thanks.

**Comment by anko** [comment]
The current directory is whichever directory you run markdown-pdf from. There's no need to edit the CSS files that come with markdown-pdf, since you can specify your own.

- - -

The following is a minimal example that works for me. In an empty directory, create these:

`package.json`:

```json
{
  "scripts": {
    "compile": "markdown-pdf --css-path custom.css test.markdown"
  },
  "dependencies": {
    "markdown-pdf": "^5.3.0"
  }
}
```

`test.markdown`:

```markdown
[this is a link](http://github.com)
```

`custom.css`:

```css
a[href]:after { content : "" }
```

Running `npm install` in that directory should install markdown-pdf.

Running `npm run compile` should run markdown-pdf using the custom CSS, producing an output PDF without a parenthesised URL after the link.

**Comment by biofractal** [comment]
We have progress :-)

I have managed to get my custom css file picked up by the npm module. Things were somewhat complicated by the fact that I am using Meteor so, just in case any future readers are interested, I got it working by first installing the [following package](https://atmospherejs.com/ostrio/meteor-root): `meteor add ostrio:meteor-root`

Then I put my `custom_pdf.css` file, containing just the css you specified, in the special  folder `private` in the root of my site. Meteor will make this file available at: `/.meteor/local/build/programs/server/assets/app/custom_pdf.css`. 

So now I can get the correct file-path in my code using the following line (coffeescript):
```javascript
cssPath = "#{Meteor.rootPath}\\assets\\app\\custom_pdf.css"
```
This generates a pdf with the links rendered as required:

![image](https://cloud.githubusercontent.com/assets/329603/9955408/a1397b22-5de8-11e5-9e64-2be6a1165f50.png)

However a new problem has now appeared. The links do not actually work. Hovering over the links does not change the cursor and they are not clickable.

Since we have got this far together I would be really grateful if you could test your version and see if if you have the same problem. 

Thanks

**Comment by anko** [comment]
Yey for progress!

As for links not being clickable, unfortunately I get the same: the "links" are just rendered as styled text, with no hyperlink embedded in the PDF (tested with [Chromium](http://www.chromium.org/Home)'s PDF plugin and [zathura](https://pwmt.org/projects/zathura/)).

In fact, the rest of this problem seems to be exactly issue #30, which is common, judging by comments there and on ariya/phantomjs#10196 (the upstream deficiency causing this for us). #30 is closed for some reason despite being unresolved; I've [asked](https://github.com/alanshaw/markdown-pdf/issues/30#issuecomment-141406325) for it to be reopened (@alanshaw?).

I'll look into this some more and post updates at #30 if I find a solution or workaround.

**Comment by biofractal** [comment]
Thanks for the update and all your help. I will close this issue now and keep an eye on #30.

**Comment by leon-anavi** [comment]
Hi,

I have just downloaded markdown-pdf and I still getting the same issue with links. I am afraid that in my case without proper links the generated PDF is useless. Is there any progress on this task?

**Comment by vn971** [comment]
I think the current behavior is extremely counter-intuitive. I mean, it just breaks markdown specification on how to visually render the text, as well as most markdown-s I write.

If there would be a vote, I would vote to render text without the explicit URL, and only put the URL in the pop-up (if it was not explicitely specified in the markdown).
