### ISSUE TITLE
GitHub Emoji Support

### ISSUE THREAD

**Issue by katamaritaco** [alanshaw/markdown-pdf#84]
I just ran a .md readme for a project, and found that the GitHub emoji's only displayed the text, and didn't render the actual emoji.

For example, `:white_large_square:` was displayed instead of :white_large_square:

**Comment by anko** [comment]
I'd be hesitant to add that, because emoji colon-sequences like `:white_large_square:`→:white_large_square: are a Github feature, not a markdown feature.

You can however use some additional tools to get those to render as you wish, by

 - passing [`remarkable-emoji`](https://www.npmjs.com/package/remarkable-emoji) as a [remarkable-plugin option](https://github.com/alanshaw/markdown-pdf#remarkable-options-and-plugins) to markdown-pdf,
 - typing the actual Unicode character (e.g. [U+2B1C for "white large square"](http://www.fileformat.info/info/unicode/char/2b1c/index.htm)), or
 - passing your markdown file through [js-emoji](https://github.com/iamcal/js-emoji).

I'd recommend the first option.

**Comment by katamaritaco** [comment]
That makes a lot of sense. I appreciate the clarification!
