### ISSUE TITLE
bookmark support  (new feature) ?

### ISSUE THREAD

**Issue by p2227** [alanshaw/markdown-pdf#99]
there's a `.md` file:

```
## title1
### subtitle titleA
### subtitle titleB
## title2
### subtitle title2-A
### subtitle title2-B
```

can this convert to pdf's bookmark and where i click it, jump to the page of the title.
just like this( foxitReader)

![bookmark](https://raw.githubusercontent.com/p2227/p2227.github.io/master/asset/bookmark.png)

**Comment by anko** [comment]
Related to #66: PhantomJS (the renderer markdown-pdf uses to convert HTML to PDF) doesn't support intra-document links yet. It also doesn't yet support generation of a table of contents required for the way your PDF reader is displaying them. (I *think* those are separate PDF metadata features.)

**Comment by v1-hermit** [comment]
I need this anyway. Isn't there any way to bookmark a pdf or would you tell me what's the day markdown-pdf will support it?

**Comment by anko** [comment]
@v1-hermit As explained in #66, we're blocked on https://github.com/ariya/phantomjs/issues/13959, and the issue seems to be even deeper within layers of libraries that I don't understand, and which development is slow. I can't see markdown-pdf supporting PDF bookmarks any time soon.

For now, a potential workaround is to add bookmark links using a separate tool, such as [those 
discussed on SuperUser here](https://superuser.com/questions/276311/how-to-import-export-and-edit-bookmarks-of-a-pdf-file). I've never tried them, but if you do, I'd be very interested to hear back.
